version: 2
jobs:
    deploy:
        docker:
            - image: attensee/s3_website
            steps:
                - run:
                    name: Deploy to S3
                    command: s3_website push

