version: 2
jobs:
    deploy:
        docker:
            - image: attensee/s3_website
        steps:
            - checkout
            - run:
                name: Deploy to S3
                command: s3_website push
workflows:
    version: 2
    push_to_s3:
        jobs:
            - deploy

