version: 2
jobs:
    deploy:
        docker:
            - image: attensee/s3_website
        working_directory: ~/arvind.xyz/
        steps:
            - run:
                name: Test working directory
                command: ls
            - run:
                name: Deploy to S3
                command: s3_website push
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy

