version: 2
jobs:
    deploy:
        docker:
            - image: attensee/s3_website
        steps:
            - run:
                name: Checkout latest source code from Bitbucket
                command: checkout
            - run:
                name: Deploy to S3
                command: s3_website push
workflows:
    version: 2
    build_and_test:
        jobs:
            - deploy

